In [1]:
import numpy as np

numpyA = np.array([1, 3, 5])
print(numpyA)
print(type(numpyA))
print(numpyA.shape)
print(numpyA[0], numpyA[1], numpyA[2])


[1 3 5]
<class 'numpy.ndarray'>
(3,)
1 3 5


In [2]:
numpyA = np.array([[1],[2], [3]])
print(numpyA)
print(type(numpyA))
print(numpyA.shape)

[[1]
 [2]
 [3]]
<class 'numpy.ndarray'>
(3, 1)


In [3]:
numpyB = np.array([[[1]], [[2]]])
print(numpyB)
print(type(numpyB))
print(numpyB.shape)
print(numpyB[0, 0], numpyB[0, 1], numpyB[0, 2])
print(numpyB[1, 0], numpyB[1, 1], numpyB[1, 2])


[[[1]]

 [[2]]]
<class 'numpy.ndarray'>
(2, 1, 1)


IndexError: index 1 is out of bounds for axis 1 with size 1

In [1]:
print([0,1])
print([1,0])

[0, 1]
[1, 0]


In [4]:
print(type(numpyB.shape))

<class 'tuple'>


In [5]:
x = numpyB.shape
print(x, type(x))

(2, 1, 1) <class 'tuple'>


In [6]:
numpyz = np.zeros((3,3))
print(numpyz)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
numpyo = np.ones((3, 3))
print(numpyo)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
numpyf = np.full((3, 3), 9)
print(numpyf)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [9]:
numpyg=np.eye(3)
print(numpyg)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
listA = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(listA[:4])
print(listA[1:6])
print(listA[7:])

[0, 1, 2, 3]
[1, 2, 3, 4, 5]
[7, 8, 9, 10]


In [11]:
print(numpyI[:2, :2])

NameError: name 'numpyI' is not defined

In [12]:
numpyBx = np.array([[1, 3, 5], [2, 4, 6], [7, 3, 2], [1, 0, 9]])
print(numpyBx.shape)

(4, 3)


In [13]:
print(numpyBx[2:,1:])

[[3 2]
 [0 9]]


In [14]:
print(numpyBx[1:])

[[2 4 6]
 [7 3 2]
 [1 0 9]]


In [15]:
print(numpyBx[1:, 1:])

[[4 6]
 [3 2]
 [0 9]]


In [16]:
print(numpyBx[1, :])

[2 4 6]


In [17]:
row0 = numpyBx[0, :]
row1 = numpyBx[1, :]
row2 = numpyBx[2, :]
row3 = numpyBx[3, :]

print(row0)
print(row1)
print(row2)
print(row3)

[1 3 5]
[2 4 6]
[7 3 2]
[1 0 9]


In [18]:
col0 = numpyBx[:,0]
col1 = numpyBx[:,1]
col2 = numpyBx[:,2]
print(col0)
print(col1)
print(col2)

[1 2 7 1]
[3 4 3 0]
[5 6 2 9]


In [19]:
numpyBx = np.array([[1, 3, 5], [2, 4, 6], [7, 3, 2], [1, 0, 9]])
print(numpyBx[[0, 1, 3], [0, 1, 2]])
print(numpyBx[0, 0])
print(numpyBx[1, 1])
print(numpyBx[3, 2])

[1 4 9]
1
4
9


In [20]:
A = np.arange(4).reshape(2,2)
print(A)

[[0 1]
 [2 3]]


In [21]:
B = np.arange(4, 12)
print(B)

[ 4  5  6  7  8  9 10 11]


In [22]:
C = np.arange(2, 20, 3)
print(C)

[ 2  5  8 11 14 17]


In [23]:
np.linspace(1, 4, 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [24]:
n = np.array([0, 1, 1, 0])
print(numpyBx[np.arange(4), n])

[1 4 3 1]


In [25]:
#numpyBx = np.array([[1, 3, 5], [2, 4, 6], [7, 3, 2], [1, 0, 9]])
Bool_index = (numpyBx > 3)
print(Bool_index)

[[False False  True]
 [False  True  True]
 [ True False False]
 [False False  True]]


In [26]:
print(numpyBx[Bool_index])

[5 4 6 7 9]


In [27]:
print(numpyBx.dtype)

int32


In [28]:
numpyG = np.array([1, 2])
print(numpyG.dtype)

int32


In [29]:
numpyH = np.array([1.2, 2.0])
print(numpyG.dtype)

int32


In [30]:
numpyH = np.array([1.2, 2.0], dtype=np.int64)
print(numpyG.dtype)

int32


In [31]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
v = np.array([9,10])
w = np.array([11, 12])

print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [32]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [33]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [34]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [35]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [36]:
print(v.dot(w))
print(np.dot(v, w))

219
219


In [37]:
print(x.dot(v))
print(np.dot(x, v))

[29. 67.]
[29. 67.]


In [38]:
print(x.dot(y))
print(np.dot(x,y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [41]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]
